const { test } = require('@playwright/test');
const { cerDoc } = require('../PomModels/cerdocPom');
const { cepDoc } = require('../PomModels/cepdocPom');
const { deviceInfoPage } = require('../PomModels/deviceInfoPom');
const { loginAndOnboardDevice } = require('../Utils/deviceOnboard');

test('CE Report Document', async ({ page }) => {

    test.setTimeout(600000);

    // ── Login + Onboard new Trocar device ─────────────────────────────────────
    await loginAndOnboardDevice(page);
    await page.waitForTimeout(5000);

    // ── Click into the newly onboarded device ─────────────────────────────────
    const deviceInfo = new deviceInfoPage(page);
    await deviceInfo.clickFirstItem();
    await page.waitForTimeout(5000);

    // ── Navigate to Clinical Evaluation ───────────────────────────────────────
    const ceReportDoc = new cerDoc(page);
    const cePlanDoc = new cepDoc(page);

    await cePlanDoc.navigateToCEP();
    await page.waitForTimeout(4000);

    // ── Expand CER accordion ──────────────────────────────────────────────────
    await ceReportDoc.openCERSection();
    await page.waitForTimeout(3000);

    // ── Fill all CER sections ─────────────────────────────────────────────────

    // 0. State of the Art — 9 richtext fields with AI
    await ceReportDoc.stateOfArtSection();
    await page.waitForTimeout(2000);

    // 1. Pre-Clinical Data — 3 tables + 2 richtext (AI)
    await ceReportDoc.preClinicalData();
    await page.waitForTimeout(2000);

    // 2. Clinical Evaluation Overview — first checkbox + equivalence justification
    await ceReportDoc.clinicalEvalOverview();
    await page.waitForTimeout(1000);

    // 3. Clinical Data Generated by Manufacturer — Yes + PMS summary AI
    await ceReportDoc.clinicalDataManufacturer();
    await page.waitForTimeout(1000);

    // 4. Clinical Data from Literature — 2 fields with AI
    await ceReportDoc.clinicalDataLiterature();
    await page.waitForTimeout(1000);

    // 5. Other Sources of Clinical Data — 1 field with AI
    await ceReportDoc.otherSourcesClinicalData();
    await page.waitForTimeout(1000);

    // 6. Summary and Appraisal — fill 3 rows, delete extras
    await ceReportDoc.summaryAppraisalClinicalData();
    await page.waitForTimeout(1000);

    // 7. Analysis of Clinical Data in Relation to GSPRs — Yes/Yes/No/No + AI
    await ceReportDoc.analysisGSPRs();
    await page.waitForTimeout(1000);

    // 8. Acceptability to the Objectives — 3 fields with AI
    await ceReportDoc.acceptabilityObjectives();
    await page.waitForTimeout(1000);

    // 9. Conclusion — AI + Yearly + date picker
    await ceReportDoc.conclusion();
    await page.waitForTimeout(1000);

    // 10. Qualifications — 2 rows + CV upload
    await ceReportDoc.qualificationsEvaluators();
    await page.waitForTimeout(1000);

    // 11. Changes — 2 rows
    await ceReportDoc.changesSection();
    await page.waitForTimeout(1000);

    // 12. Equivalence Table — 5 char rows + 4 justification rows
    await ceReportDoc.equivalenceTable();
    await page.waitForTimeout(1000);

    // ── Save Draft + Mark Section Complete ────────────────────────────────────
    await ceReportDoc.cerSaveAndComplete();

});
