const { test } = require('@playwright/test');

test('Full CER form inspection', async ({ page }) => {
    test.setTimeout(300000);

    // ── Login (skip if already logged in) ────────────────────────────────────
    await page.goto('https://web.staging.obodux.boris-software.com');
    await page.waitForTimeout(4000);
    const emailField = page.getByLabel('Email');
    if (await emailField.isVisible({ timeout: 5000 }).catch(() => false)) {
        await emailField.fill('editor-stag.1@yopmail.com');
        await page.getByLabel('Password').fill('abcd@TEST123');
        await page.getByRole('button', { name: /sign in/i }).click();
        await page.waitForTimeout(5000);
    }

    // ── Open existing Trocar device ───────────────────────────────────────────
    await page.getByText('Trocar').first().click();
    await page.waitForTimeout(4000);

    // ── Navigate to CER form ──────────────────────────────────────────────────
    await page.getByRole('link', { name: 'Clinical Evaluation' }).click();
    await page.waitForTimeout(3000);

    // Expand CER accordion (h3 button index 1)
    const h3Buttons = page.locator('h3 button');
    console.log(`h3 buttons total: ${await h3Buttons.count()}`);
    await h3Buttons.nth(1).click();
    await page.waitForTimeout(2000);

    // Try to navigate to CER report page
    const currentUrl = page.url();
    const reportUrl = currentUrl.includes('/clinical-evaluation/plan')
        ? currentUrl.replace('/clinical-evaluation/plan', '/clinical-evaluation/report')
        : currentUrl;
    if (currentUrl !== reportUrl) {
        await page.goto(reportUrl);
        await page.waitForTimeout(4000);
    }
    console.log(`\nCurrent URL: ${page.url()}\n`);

    // ── Global counts BEFORE scrolling ────────────────────────────────────────
    const allBorderFields = page.locator('[class*="border px-3"]');
    const allEditables = page.locator('[contenteditable="true"]');
    const allRadioGroups = page.locator('[role="radiogroup"]');
    const allRadios = page.locator('input[type="radio"]');
    const allCheckboxes = page.locator('input[type="checkbox"]');
    const allTables = page.locator('table');

    console.log('═══ GLOBAL PAGE ELEMENT COUNTS ═══');
    console.log(`  [class*="border px-3"] fields: ${await allBorderFields.count()}`);
    console.log(`  [contenteditable="true"]:        ${await allEditables.count()}`);
    console.log(`  [role="radiogroup"]:             ${await allRadioGroups.count()}`);
    console.log(`  input[type="radio"]:             ${await allRadios.count()}`);
    console.log(`  input[type="checkbox"]:          ${await allCheckboxes.count()}`);
    console.log(`  tables:                          ${await allTables.count()}`);

    // ── Print global index of every border-px-3 field ────────────────────────
    console.log('\n═══ BORDER-PX-3 FIELD INDEX MAP ═══');
    const fieldCount = await allBorderFields.count();
    for (let i = 0; i < fieldCount; i++) {
        const el = allBorderFields.nth(i);
        const bbox = await el.boundingBox();
        const text = (await el.innerText()).substring(0, 60).replace(/\n/g, ' ').trim();
        console.log(`  field[${i}]  y=${bbox ? Math.round(bbox.y) : '?'}  "${text}"`);
    }

    // ── Print global index of every radiogroup ───────────────────────────────
    console.log('\n═══ RADIOGROUP INDEX MAP ═══');
    const rgCount = await allRadioGroups.count();
    for (let i = 0; i < rgCount; i++) {
        const el = allRadioGroups.nth(i);
        const bbox = await el.boundingBox();
        const text = (await el.innerText()).substring(0, 80).replace(/\n/g, ' ').trim();
        console.log(`  radiogroup[${i}]  y=${bbox ? Math.round(bbox.y) : '?'}  "${text}"`);
    }

    // ── Walk each section by scrolling and logging what's visible ─────────────
    const sections = [
        { name: 'State of the Art',                          scroll: 115  },
        { name: 'Pre-Clinical Data',                         scroll: 1526 },
        { name: 'Clinical Evaluation Overview',              scroll: 2959 },
        { name: 'Clinical Data Generated by Manufacturer',   scroll: 3580 },
        { name: 'Clinical Data from Literature',             scroll: 3940 },
        { name: 'Other Sources of Clinical Data',            scroll: 4318 },
        { name: 'Summary and Appraisal',                     scroll: 4565 },
        { name: 'Analysis GSPRs',                            scroll: 5109 },
        { name: 'Acceptability to the Objectives',           scroll: 6263 },
        { name: 'Conclusion',                                scroll: 7076 },
        { name: 'Qualifications of Evaluators',              scroll: 7583 },
        { name: 'Changes',                                   scroll: 8010 },
        { name: 'Equivalence Table',                         scroll: 8411 },
    ];

    const container = page.locator('.flex-1.overflow-y-auto');

    for (const sec of sections) {
        await page.evaluate((p) => {
            const c = document.querySelector('.flex-1.overflow-y-auto');
            if (c) c.scrollTop = p;
        }, sec.scroll);
        await page.waitForTimeout(800);

        // Take screenshot
        const slug = sec.name.replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 30);
        await page.screenshot({ path: `inspect2-${slug}.png`, fullPage: false });

        // Count visible border-px-3 fields (by bounding box in container viewport)
        const containerBox = await container.boundingBox();
        let visibleFields = [];
        for (let i = 0; i < fieldCount; i++) {
            const bbox = await allBorderFields.nth(i).boundingBox();
            if (bbox && containerBox &&
                bbox.y >= containerBox.y - 10 &&
                bbox.y <= containerBox.y + containerBox.height + 10) {
                visibleFields.push(i);
            }
        }

        let visibleGroups = [];
        for (let i = 0; i < rgCount; i++) {
            const bbox = await allRadioGroups.nth(i).boundingBox();
            if (bbox && containerBox &&
                bbox.y >= containerBox.y - 10 &&
                bbox.y <= containerBox.y + containerBox.height + 10) {
                visibleGroups.push(i);
            }
        }

        // Count table rows visible
        const tableCount = await allTables.count();
        let visibleTables = [];
        for (let i = 0; i < tableCount; i++) {
            const bbox = await allTables.nth(i).boundingBox();
            if (bbox && containerBox &&
                bbox.y >= containerBox.y - 50 &&
                bbox.y <= containerBox.y + containerBox.height + 50) {
                const headers = await allTables.nth(i).locator('th').allInnerTexts();
                visibleTables.push({ idx: i, headers });
            }
        }

        const checkboxCount = await page.locator('input[type="checkbox"]:visible').count();
        const radioCount    = await page.locator('input[type="radio"]:visible').count();

        console.log(`\n─── ${sec.name} (scroll=${sec.scroll}) ───`);
        console.log(`  visible border-px-3 field indices: [${visibleFields.join(', ')}]`);
        console.log(`  visible radiogroup indices:         [${visibleGroups.join(', ')}]`);
        console.log(`  visible checkboxes: ${checkboxCount},  radios: ${radioCount}`);
        if (visibleTables.length) {
            for (const t of visibleTables) {
                console.log(`  table[${t.idx}] headers: ${JSON.stringify(t.headers)}`);
            }
        }
    }

    console.log('\n\nInspection complete. Screenshots saved.');
});
